# This is an example of a parameters file
# It is written according to the YAML-convention (www.yaml.org) and is checked by the code for consistency.
# Three types of parameters are possible and reflected in the structure of the document:
#
# Parameter category:
#   Setting Name: <value>
#
# The three parameter categories are:
# - setting: Setting to use for preprocessing and class specific settings. if no <value> is specified, the value for
#   this setting is set to None.
# - featureClass: Feature class to enable, <value> is list of strings representing enabled features. If no <value> is
#   specified or <value> is an empty list ('[]'), all features for this class are enabled.
# - imageType: image types to calculate features on. <value> is custom kwarg settings (dictionary). if <value> is an
#   empty dictionary ('{}'), no custom settings are added for this input image.
#
# Some parameters have a limited list of possible values. Where this is the case, possible values are listed in the
# package documentation

# Settings to use, possible settings are listed in the documentation (section "Customizing the extraction").
setting:
  # Resampling:
  label: 1
  interpolator: 'sitkLinear' # This is an enumerated value, here None is not allowed
  resampledPixelSpacing: [2,2,2]# This disables resampling, as it is interpreted as None, to enable it, specify spacing in x, y, z as [x, y , z]
  padDistance: 5
  preCrop: True
  #Resegmentation
  resegmentRange: [-1000,400]
  # Discretiztion:
  binWidth: 25
  # First order-specific settings:
  voxelArrayShift: 0
  #GLCM & GLRLM-specific settings
  weightingNorm: 'no_weighting'
  # GLDM-specific settings:
  gldm_a: 0
  
# Image types to use: "Original" for unfiltered image, for possible filters, see documentation.
imageType:
  Original: {} # for dictionaries / mappings, None values are not allowed, '{}' is interpreted as an empty dictionary 
  
# Featureclasses, from which features must be calculated. If a featureclass is not mentioned, no features are calculated
# for that class. Otherwise, the specified features are calculated, or, if none are specified, all are calculated (excluding redundant/deprecated features).
featureClass:
  glcm: 
  glrlm: # for lists none values are allowed, in this case, all features are enabled

  
